### PR TITLE
torch.Tensor changed to torch.tensor

### PR DESCRIPTION
**Pull request by oguzhanbsolak**
torch.Tensor was split into torch.tensor and torch.empty. To convert a variable to a tensor, now torch.tensor should be used.

### CODE REVIEW

**Comment by seldauyanik-maxim** [comment]
We do have many existing torch.Tensor usages in train.py, ai8x.py, dataloaders etc. Do they need the same update?

**Comment by oguzhanbsolak** [comment]
From my trials, it seems like the problematic case occurs when we use torch.Tensor(int). It will create a zeros array with the size of the declared int, instead of creating a tensor with that integer. Usage with arrays of integers and floats seems to be safe (e.g. torch.Tensor([int]), torch.Tensor([float]). Therefore, most of our use cases seem safe. However, torch.tensor() method seems safer to use for the variable to tensor conversation tasks as it will always accept the input as data. Also, we may use torch.zeros or torch.zeros_like methods to create zero array tensors with specified shapes.

**Review by alicangok — APPROVED** [review]
Looks good.

Similar comments are given [here](https://discuss.pytorch.org/t/difference-between-torch-tensor-and-torch-tensor/106816/4)

Perhaps we should think about using torch.zeros() (or other creation ops) instead of torch.Tensor() in the rest of the repository, since that's the official [recommendation](https://pytorch.org/docs/stable/tensors.html#torch.Tensor)

**Comment by oguzhanbsolak** [comment]
I agree these lines should be updated. I will check all torch.Tensor usages and replace them with torch.tensor if it's intended for tensor conversion.

**Comment by alicangok** [comment]
It looks like many calls to torch.tensor() were changed to torch.Tensor() in [this commit](https://github.com/MaximIntegratedAI/ai8x-training/commit/8413da089b23cb5c82b88d9492812668c229edf7) because of the linter at the time. Are we using the same linter now?

**Comment by oguzhanbsolak** [comment]
Other files in the repo included in the new commits

**Review by alicangok — APPROVED** [review]
Looks better :)

**Comment by oguzhanbsolak** [comment]
To use --kernel-stats, kernel_stats tensors must be on the same device as the network. 
The latest commits include this change and some linter changes. Also, the last commit tested for classification and regression tasks up to KAT including all steps.

**Review by rotx-maxim — APPROVED** [review]

**Pull request merged**
